### ISSUE TITLE
How to enable mosfet outputs with a 12V power supply (only for testing)

### ISSUE THREAD

**Issue by karponline** [FYSETC/FYSETC-SPIDER#10]
I have a problem with PWM enabled mosfet outputs (1 for HotBed, 3 for Heat-End, 3 for fans). I checked with a meter and there is no voltage on any of them. The only thing that comes to mind is too low voltage to drive the mosfet because I use a 12V power supply. I was able to get all the stepper motors, limit sensors, temperature sensors and the display running. Everything works with this power supply. I also wonder how to properly connect the External MOS module V1.0

**Comment by eliwong** [comment]
Spider's mosfet is driven by the onboard 12V (DC-DC), but the 12V circuit on the board requires a minimum input of 15V to work properly, so if you use a 12V input, you can mark it as "24V" and " The 12V" pin header is shorted.
![image](https://user-images.githubusercontent.com/21209689/121283434-ada59580-c90d-11eb-941c-413e519b0397.png)

**Comment by karponline** [comment]
Thanks a lot for your help it works. The photos show my motherboard running during the first tests. Everything works very well. I have already ordered a new 24V power supply and I treat this solution as a test. I don't want to overload the mosfets with too much current. I recommend this product to everyone. 

![20210609_222504](https://user-images.githubusercontent.com/22419502/121482314-549d3680-c9cd-11eb-9e7e-281c1dc34896.jpg)
![20210609_222402](https://user-images.githubusercontent.com/22419502/121482353-6383e900-c9cd-11eb-888e-298ddb6b2350.jpg)
