### ISSUE TITLE
[Documentation] Spider 2.2 pinout errata

### ISSUE THREAD

**Issue by numindast** [FYSETC/FYSETC-SPIDER#112]
https://github.com/FYSETC/FYSETC-SPIDER/blob/main/images/Spider_V2.2_Pinout.jpg

The "PI PWR & UART" block has an incorrect label on this screenshot. In the top row, we have "nc nc nc nc 5V" when that last element is actually GND as tested with a multimeter.

This had me thinking the supplied cable would be a highly effective short circuit shunt. Turns out it's just mislabeled on the JPG.

**Comment by GerogeFu** [comment]
Thanks, updated
