### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by shiftingtech** [FYSETC/FYSETC-SPIDER#12]
Several of the key diagrams are currently badly broken, both on github and the wiki.  For example, 
https://raw.githubusercontent.com/FYSETC/FYSETC-SPIDER/main/images/Spider_wiring.svg
currently renders in Chrome as
![image](https://user-images.githubusercontent.com/53156353/120955146-fa228280-c70d-11eb-9842-c995a4d00ced.png)

**Comment by GerogeFu** [comment]
Try to download the whole project ,then check it in your computer

**Comment by shiftingtech** [comment]
I'm not saying you're wrong, but you really shouldn't have to download the whole thing just to view the images.  Maybe you could post some JPEGs or something, just for ease of accessibility?

**Comment by GerogeFu** [comment]
Ah, thanks for your reminding.
