### ISSUE TITLE
3.3V supply failed, how to repair?

### ISSUE THREAD

**Issue by khrazik** [FYSETC/FYSETC-SPIDER#14]
Hi, the board was working when arrived. I've installed klipper and without steppers, everything ran fine. X/Y stepsticks tested fine – but when I installed Z and E, I lost 3.3V power and the board does not boot anymore.

The 3.3V LED is not lit up and I have tested 0.13V on the 3.3V pin next to BT0.
I would like to restore the board to good working order. 

Based on this information, could you tell me which component/s were the most likely to fail and what should I start testing/replacing? I can solder SMD components. Photo attached for reference:

 ![20210615_180311](https://user-images.githubusercontent.com/44820492/122090621-3fc70580-ce08-11eb-9ae7-4c423761a14d.jpg)

**Comment by CompaxChris** [comment]
How was this solved? Seems like I maybe have a similar problem
