### ISSUE TITLE
Water flow sensor

### ISSUE THREAD

**Issue by Cabinfourus** [FYSETC/FYSETC-SPIDER#145]
I have a 3D printer with a water cooled hot end. I want to connect a water flow sensor to the Spider V2.2 to monitor water flow and stop the printer if water is not flowing properly. Any ideas? Can I use an endstop? The water flow sensor uses a pusle signal to monitor the flow.

**Comment by eliwong** [comment]
The position of the limit switch can be used. They can be used as standard input and output interfaces. If an SD card is not used, the SPI pin next to it can also be used as a normal IO.
