### ISSUE TITLE
Spider 3.0 sensorless homing

### ISSUE THREAD

**Issue by Gabriel121217** [FYSETC/FYSETC-SPIDER#146]
Does anyone know how to enable sensorless homing on the spider 3? I tried searching for diag pins but I am unable to find them.

**Comment by cyberjak2k** [comment]
Look directly under each stepper driver there are 2 pins clearly marked diag. Put a jumper on the pins to enable sensorless homing , no jumper to use endstop switch

**Comment by ozzman39** [comment]
do you have to put jumpers on th endstops as well? or just diag? and if so were  on the endstopas

**Comment by cyberjak2k** [comment]
Only the diagnostic jumpers. do not put jumpers on the end stop pins
