### ISSUE TITLE
Sensorless homing instructions on pinout diagram

### ISSUE THREAD

**Issue by paulstimpson** [FYSETC/FYSETC-SPIDER#16]
The instructions in the green box on the pinout diagram located [here](https://github.com/FYSETC/FYSETC-SPIDER/blob/main/images/Spider_wiring.jpg) are not written in good English.

They currently read "If need the Sensor-less homing, the corresponding jumper here should be install."

![image](https://user-images.githubusercontent.com/2911040/122895104-b3ed3600-d33f-11eb-9a19-0a42e2226849.png)

I suggest the following wording which I think is better, "If sensorless homing is required on an axis, install a jumper on the corresponding pins here"

I also  notice that the green box only covers the X and Y pins, not the Z pins. Is this incorrect or is the board not capable of Z-axis sensorless homing?

**Comment by GerogeFu** [comment]
Updated. Thanks.
