### ISSUE TITLE
Probe Problem

### ISSUE THREAD

**Issue by dodasch** [FYSETC/FYSETC-SPIDER#24]
I have Problems with my Inductive Probe. 
My Probe is always Triggered.

I've been using a PNP-Probe.

I measured 3.3V between Pin PA3 & GND. 

So i need an NPN Probe, right?

**Comment by dodasch** [comment]
Here is my Klipper config:

https://pastebin.com/embdmx9J

**Comment by photocromax** [comment]
I guess you do need a NPN, maybe there is a way to connect a PNP too, but not sure how.

**Comment by dodasch** [comment]
Okay this Issue can be closed, but it should be marked on the wiring that you only can use a NPN Probe.

**Comment by sbusso** [comment]
having the same problem, PA3 should provide 24V, did you solve your issue?
