### ISSUE TITLE
Pinout diagram shows MISO twice on EXP1

### ISSUE THREAD

**Issue by foleac** [FYSETC/FYSETC-SPIDER#26]
https://github.com/FYSETC/FYSETC-SPIDER/blob/main/images/Spider_V1.0_Pinout.jpg shows MISO for pins 1 (top right - connector's orientation not image) and 6 (middle bottom). I assume one of those should be MOSI. Is that correct?

**Comment by GerogeFu** [comment]
Yes, the 6 is MOSI. You can check the pin at the back of Spider board.

**Comment by GerogeFu** [comment]
Pinout jpg have been updated.
