### ISSUE TITLE
Maybe Wrong Config Info in printer.cfg for Inductive Probe

### ISSUE THREAD

**Issue by xenon2008** [FYSETC/FYSETC-SPIDER#28]
Hello together!

I have a Spider Board and currently creating my config for my first own Voron with an inductive Probe! (a VINDA NC Probe from vonWange)
I used the default config from here:
https://github.com/FYSETC/FYSETC-SPIDER/blob/main/firmware/Klipper/printer.cfg

And i had to remove the ! from "^!PA3", so now it is "^PA3"
Then the Trigger / Open Status are correct, with a ! the are inverted.

Could it be that the Description in the Config is wrong?
In my opinion the description is reversed! With ! it is a NO Probe and without! is it an NC Probe
could this be?

Kind Regards from Austria

**Comment by GerogeFu** [comment]
I think you are right, the default printer.cfg is for PL08N Probe, it is NO Probe too. I will update the comment.

**Comment by xenon2008** [comment]
Thanks ;)
