### ISSUE TITLE
BigTreeTech TFT70 screen compatibility with RS232 port

### ISSUE THREAD

**Issue by Recoil1980** [FYSETC/FYSETC-SPIDER#30]
I am looking at getting the Fysetc Spider 1.1 as a replacement for my BTT SKR 1.4 Turbo, and would like to find out if the board is compatible with my screen (BTT TFT70) with the RS232 connector from the screen, or if the EXP ports have to be used instead?

**Comment by GerogeFu** [comment]
There is UART at the middle of Spider, you can check the pin define at the back of the board.
![image](https://user-images.githubusercontent.com/7496375/127249931-18800ae4-6ceb-40dd-8f77-0a65b26aefee.png)

**Comment by Recoil1980** [comment]
Thank you!
