### ISSUE TITLE
New board won’t connect

### ISSUE THREAD

**Issue by shadowdro** [FYSETC/FYSETC-SPIDER#54]
I have a brand new board that has been in the antistatic bag until last night. I recently purchased the Voron 2.4 kit. I am unable to get it into dfu mode. I followed the instructions on the wiki.￼￼ I am unable to get it into DFU mode. Since the 32K boot loader supposed to be on the board since June I tried flashing the 32K uart via SD card.￼, which appears to have failed. And then tried doing the same for USB, and neither can connect to the pi.￼ right now when I put the firmware on an SD and put it onto the board it stays flashing for over 40 minutes. ￼after looking through these issue requests I tried clearing the power on the board and removing the stepper drivers and everything except for the two jumpers to enter DFU mode. It is still unable to connect and does not seem to respond via any commands. Please assist.￼

**Comment by shadowdro** [comment]
![image](https://user-images.githubusercontent.com/66856201/139542340-7137034e-5c5d-43e8-8a5c-3fb635f9b0c7.jpeg)

**Comment by RcTomcat1** [comment]
Same here. Just connected my board for the first time. Nothing. Tried with a Linux and Windows system, three different usb cables, 24 and 5v....no dfu ....

**Comment by shadowdro** [comment]
￼￼someone in the Discord said they received a charge only usb cable. I'm going to try another usb cable and  see if that fixes B it.

**Comment by shadowdro** [comment]
Tried new USB cable.... it connected... Kit came with charge only USB....
