### ISSUE TITLE
TMC 'stepper_x' reports error: GSTAT: 00000004 uv_cp=1

### ISSUE THREAD

**Issue by skfab** [FYSETC/FYSETC-SPIDER#66]
I am getting this error on my Voron2.4 Spider 1.1 with 2209 3.1 Fysetc stepsticks, After starting a print I will get it on ether the x or y axis. I have replaced the x and y 2209s with new ones but no change. Any help would much appreciated. 

TMC 'stepper_x' reports error: GSTAT:
00000004 uv_cp=1 (Undervoltage!)

**Comment by skfab** [comment]
I changed the stealthchop_threshold from 1  to 0 and raised the current settings, it seems to be working now.

**Comment by bogeyf14** [comment]
I am having the same issue on my spider v1.0 with tmc 2209 3.1. I also have stealthchop_threshold set to 1 and motor current is set to about 85% of rated current

**Comment by dawidmpunkt** [comment]
> I am having the same issue on my spider v1.0 with tmc 2209 3.1. I also have stealthchop_threshold set to 1 and motor current is set to about 85% of rated current

Because I was also having this issue: A faulty stepper cable also causes this error. Try another stepper cable.

**Comment by warrenfalk** [comment]
I received this same error a few days ago due to what turned out to be a bad 2209 (for anyone else coming here googling this error message). I ended up swapping slots with a working 2209 just to confirm the issue and then replaced it with a new one and the problem is resolved. The 2209 had worked fine for a couple years before giving out.

**Comment by P1P1Monster** [comment]
Same situation, Cable problem or stepper driver broken both may cause this issue

**Comment by WaschBaer0395** [comment]
same issue but its neither the stepper driver ( tested ) nor the cable ( swapped with a different one ) or the motor ( also swapped with a motor not throwing this error ) 
this only happens during homing sensorless sometimes and only way to fix it is to restart the whole printer

**Comment by petercabra** [comment]
I am having the same issue, happens randomly when homing sensorless, mostly on Y axis (voron 2.4r2). Only way to fix it is to fix it is restarting the whole printer.

**Comment by Galnomac** [comment]
Excuse me.. The same thing is happening to me in a Voron 2.4. E changed driver from X and Y to others Y remains the same.. how did they solve it???
