### ISSUE TITLE
bl touch-spider 2.2

### ISSUE THREAD

**Issue by hwystitch** [FYSETC/FYSETC-SPIDER#75]
So the two pictures for the 2.2 have conflicting info for pins. the one here [https://github.com/FYSETC/FYSETC-SPIDER/blob/main/images/Spider_v2.2_wiring.jpg](url) shows the ground as the first and fourth pin with the pwm pin going off to nowhere.... and the wiring pic here [https://raw.githubusercontent.com/FYSETC/FYSETC-SPIDER/main/images/Spider_V2.2_Pinout.jpg](url) shows the grounds as 2 and 5. So which way to actually wire the bltouch. Really dont wanna fry my bl touc or mainboard.

Thanks

**Comment by GerogeFu** [comment]
I just update the pinout jpg, actually you can check the pin label at the back of the board. Thanks

**Comment by hwystitch** [comment]
thanks
